// German site tags (de.dblegends.net) -> English tag names used by the
// roster pipeline. Battle styles pass through in English so role detection
// works; import-roster.js later filters and renames to the displayed tags.
'use strict';

module.exports = {
  'Schlagangriffstyp': 'Melee Type',
  'Fernangriffstyp': 'Ranged Type',
  'Verteidigungstyp': 'Defense Type',
  'Unterstützungstyp': 'Support Type',
  'Saiyajin': 'Saiyan',
  'Halb-Saiyajin': 'Hybrid Saiyan',
  'Son-Familie': 'Son Family',
  'Vegeta-Clan': 'Vegeta Clan',
  'Göttliches Ki': 'God Ki',
  'Fusionierter Kämpfer': 'Fusion Warrior',
  'Zukunft': 'Future',
  'GT': 'GT',
  'DAIMA': 'DAIMA',
  'Erneuerung': 'Regeneration',
  'Cyborg': 'Android',
  'Böse Abstammung': 'Lineage of Evil',
  'Mächtiger Feind': 'Powerful Opponent',
  'Kinoversion-Saga': 'Sagas From the Movies',
  'Kinoversion-Saga (SUPER HERO)': 'Sagas From the Movies',
  'Mädels': 'Girls',
  'Weiblich': 'Female',
  'Super-Saiyajin': 'Super Saiyan',
  'Super-Saiyajin 2': 'Super Saiyan 2',
  'Super-Saiyajin 3': 'Super Saiyan 3',
  'Super-Saiyajin 4': 'Super Saiyan 4',
  'Super-Saiyajin-Gott': 'Super Saiyan God',
  'Super-Saiyajin Blue': 'Super Saiyan God SS',
  'Super-Saiyajin Rosé': 'Super Saiyan Rosé',
  'Verwandelter Kämpfer': 'Transforming Warrior',
  'Kämpfer des Jenseits': 'Otherworld Warrior',
  'Freezer-Armee': 'Frieza Force',
  'Ginyu-Kommando': 'Ginyu Force',
  'Namekianer': 'Namekian',
  'Kids': 'Kids',
  'Minion': 'Minion',
  'Gegnerisches Universum': 'Rival Universe',
  'Universums-Repräsentant': 'Universe Rep',
  '2. Universum': 'Universe 2',
  '4. Universum': 'Universe 4',
  '6. Universum': 'Universe 6',
  '9. Universum': 'Universe 9',
  '11. Universum': 'Universe 11',
  'Potara': 'Potara',
  'Superkämpfer': 'Super Warrior',
  'Bardocks Team': 'Team Bardock',
  'Volk der Hera': 'Hera Clan',
  'Teufelsdrachen': 'Shadow Dragon',
  'Legends Road': 'Legends Road',
  'Spiel-Original': 'Game Originals',
  'Engel': 'Angel',
  'Gott der Zerstörung': 'God of Destruction',
  'Waffenträger': 'Weapon Wielder',
  'Turles-Armee': 'Turles Crusher Corps',
};
